export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const USERS = 'USERS'
export const USERPROFILE = 'USERPROFILE'
export const USERNAME = 'USERNAME'
export const ALLPOSTS = 'ALLPOSTS'